/** Canonical English UI strings used for Google Translate. */
export const UI_STRINGS = [
  "Translating…",
  "O₃ concentration",
  "A full moon brightens the night — clear skies will feel luminous.",
  "A new moon night — darker skies favor stargazing if clouds stay away.",
  "Calm weather forecasts",
  "Use my location",
  "Search for a city…",
  "Search for a city",
  "Searching cities…",
  "No cities found",
  "Favorites",
  "Share",
  "Copied",
  "Refresh",
  "Updated just now",
  "Waiting for data…",
  "Current conditions",
  "Feels like",
  "Weather alerts",
  "Based on current conditions",
  "What to wear",
  "Practical outfit tips",
  "No notable alerts right now — conditions look manageable.",
  "Today's details",
  "Humidity, wind, pressure, and more",
  "Humidity",
  "Relative humidity",
  "Wind",
  "Pressure",
  "Surface pressure",
  "Visibility",
  "Horizontal visibility",
  "Precipitation",
  "Chance of precipitation",
  "UV index",
  "Daily maximum",
  "Sunrise",
  "Sunset",
  "Local time",
  "Hourly forecast",
  "Next 24 hours",
  "Now",
  "7-day forecast",
  "Weekly outlook",
  "Today",
  "Trends",
  "Temperature and precipitation probability",
  "Air quality",
  "Live AQI, particles, and ozone",
  "European AQI",
  "US AQI",
  "US scale",
  "Fine particles",
  "Ozone",
  "Compare cities",
  "Side-by-side look at up to three favorites",
  "Save at least two favorite cities to compare them side by side.",
  "Location map",
  "Selected city",
  "Rain radar on",
  "Rain radar off",
  "Radar zoom limited",
  "Moon phase",
  "Illumination",
  "Switch to light theme",
  "Switch to dark theme",
  "Add current city to favorites",
  "Remove current city from favorites",
  "Favorite cities",
  "No favorites yet. Tap the heart to save a city.",
  "City search language",
  "Copy shareable city link",
  "Unable to load weather",
  "Something went wrong while fetching the forecast.",
  "Try again",
  "City not found",
  "Try a different spelling or nearby city name.",
  "Location unavailable",
  "We couldn’t access your current location.",
  "Map unavailable",
  "Google Maps could not be loaded for this location.",
  "Maps API key missing",
  "Add NEXT_PUBLIC_GOOGLE_MAPS_API_KEY to your .env.local file to enable the map.",
  "No weather yet",
  "Search for a city to see the forecast.",
  "Retry air quality",
  "Good",
  "Fair",
  "Moderate",
  "Poor",
  "Very poor",
  "Extremely poor",
  "Low",
  "High",
  "Very high",
  "Extreme",
  "Clear",
  "Mostly clear",
  "Partly cloudy",
  "Overcast",
  "Fog",
  "Drizzle",
  "Rain",
  "Freezing rain",
  "Snow",
  "Thunderstorm",
  "A calm and pleasant afternoon",
  "Rain may arrive later today",
  "Clear skies throughout the evening",
  "Warm and clear — a bright afternoon",
  "Warm and clear — a bright evening",
  "Partly cloudy with pleasant intervals of sun",
  "Partly cloudy skies through the evening",
  "A soft, overcast sky for the day ahead",
  "Foggy conditions — visibility may be limited",
  "Light drizzle may linger through the day",
  "Icy conditions possible — take care outdoors",
  "Snowy conditions expected — dress warmly",
  "Thunderstorms may develop — stay weather-aware",
  "A calm outlook for the hours ahead",
  "High UV index",
  "Seek shade midday and use sunscreen if outdoors.",
  "Thunderstorm risk",
  "Seek sturdy shelter and avoid open areas if storms develop.",
  "Wintry conditions",
  "Roads may be slippery — allow extra travel time.",
  "Reduced visibility",
  "Drive carefully and use low-beam lights in fog.",
  "Rain likely",
  "Keep an umbrella or rain jacket handy today.",
  "Strong winds",
  "Secure loose outdoor items and watch for gusts.",
  "Heat caution",
  "Stay hydrated and take breaks in cooler spaces.",
  "Cold conditions",
  "Layer up and cover extremities if heading outside.",
  "Light, breathable fabrics",
  "Sunglasses and a sun hat",
  "Comfortable short sleeves or a light shirt",
  "A light jacket or long sleeves",
  "A warm coat and closed shoes",
  "Heavy layers, gloves, and a warm hat",
  "Waterproof outer layer or umbrella",
  "A wind-resistant layer",
  "SPF sunscreen for exposed skin",
  "Moisture-wicking clothes for humidity",
  "A light extra layer for cooler nights",
  "What to wear:",
  "New moon",
  "Waxing crescent",
  "First quarter",
  "Waxing gibbous",
  "Full moon",
  "Waning gibbous",
  "Last quarter",
  "Waning crescent",
  "Weather data by",
  "Weather & air quality by",
  "Rain radar by",
  "Maps by Google when configured.",
  "Showing your last city or Dhaka instead.",
  "Location permission was denied.",
  "Current location",
  "Air quality is satisfactory",
  "Acceptable for most people",
  "Sensitive groups may notice effects",
  "Consider limiting outdoor exertion",
  "Reduce prolonged outdoor activity",
  "Avoid outdoor exertion if possible",
  "No data",
  "Unknown",
  "Calm environmental insights",
  "Dashboards",
  "Weather",
  "Earthquakes",
  "Air Quality",
  "Disaster & earthquake monitoring",
  "Live seismic activity with risk indicators and regional filters",
  "Earthquake filters",
  "Monitoring near",
  "Filter recent seismic activity",
  "Time window",
  "7 days",
  "30 days",
  "Min magnitude",
  "Max depth",
  "Any depth",
  "≤ 70 km",
  "≤ 300 km",
  "Region radius",
  "Worldwide",
  "500 km",
  "1000 km",
  "2000 km",
  "Saved regions",
  "Unable to load earthquakes",
  "Recent earthquakes",
  "events",
  "No earthquakes match these filters.",
  "Event details",
  "Select an earthquake to view details.",
  "Magnitude",
  "Depth",
  "Time",
  "Shallow",
  "Intermediate",
  "Deep",
  "Tsunami warning flag reported for this event.",
  "View on USGS",
  "Earthquake map",
  "Markers sized by magnitude and colored by risk",
  "Earthquake timeline",
  "Event count and peak magnitude over time",
  "No timeline data for these filters.",
  "Events",
  "Max magnitude",
  "Emergency guidance",
  "Simple safety steps for seismic events",
  "Before",
  "During",
  "After",
  "Secure heavy furniture and know safe spots in each room.",
  "Prepare a small emergency kit with water, flashlight, and whistle.",
  "Practice Drop, Cover, and Hold On with your household.",
  "Drop to the ground, take cover under sturdy furniture, and hold on.",
  "Stay away from windows, exterior walls, and falling objects.",
  "If outdoors, move to an open area away from buildings and power lines.",
  "Check yourself and others for injuries and hazards like gas leaks.",
  "Expect aftershocks and move carefully when exiting damaged areas.",
  "Follow official guidance and avoid coastal areas if a tsunami is possible.",
  "Minor",
  "Light",
  "Strong",
  "Major",
  "Great",
  "Air quality & pollution tracker",
  "Air Quality Index",
  "Unable to load air quality",
  "Pollutant levels",
  "Current particle and gas concentrations",
  "Coarse particles",
  "Carbon monoxide",
  "Nitrogen dioxide",
  "Sulphur dioxide",
  "Hourly pollution charts",
  "PM2.5, PM10, ozone, and carbon monoxide trends",
  "No hourly pollution data available.",
  "Health recommendations",
  "Save at least two favorite cities to compare air quality.",
  "Side-by-side AQI for up to three favorites",
  "Air quality is good — outdoor activities are fine for most people.",
  "Open windows for fresh ventilation when convenient.",
  "Air quality is acceptable for most people.",
  "Sensitive individuals may prefer lighter outdoor exertion.",
  "Sensitive groups should reduce prolonged or heavy outdoor activity.",
  "Consider shorter outdoor sessions and monitor how you feel.",
  "Limit outdoor exertion, especially for children and older adults.",
  "Keep indoor air cleaner by closing windows during peak pollution.",
  "Avoid outdoor exercise and reduce time outdoors when possible.",
  "Use a well-fitting mask outdoors if you must travel through polluted air.",
  "Monitor local air quality updates before planning outdoor activity.",
  "PM2.5 is elevated — fine particles can irritate lungs and heart.",
  "Ozone is elevated — schedule outdoor activity for early morning if needed.",
  "Next 48 hours",
  "Hourly range",
  "Sustained wind",
  "Wind direction",
  "Compass direction",
  "Cloud cover",
  "Sky coverage",
  "Wind gusts",
  "Peak gust speed",
  "Dew point",
  "Air moisture point",
  "Apparent temperature",
  "Astronomy",
  "Sun and moon details",
  "Day length",
  "Moon illumination",
  "Daylight progress",
  "Civil dawn",
  "Civil dusk",
  "Moonrise",
  "Moonset",
  "Next full moon",
  "Next new moon",
  "UV insights",
  "Sun safety and exposure guidance",
  "Current UV",
  "Risk level",
  "Suggested safe time",
  "minutes",
  "Peak UV window",
  "UV data unavailable.",
  "Avoid midday sun, use SPF 50+, and seek full shade.",
  "Limit direct sun exposure and reapply sunscreen often.",
  "Use SPF 30+, a hat, and reduce midday exposure.",
  "Use sunscreen for longer outdoor sessions.",
  "Low risk, but sun protection is still useful outdoors.",
  "Rain outlook",
  "Precipitation chance and expected amount",
  "Current rain chance",
  "Next rain",
  "Expected amount (12h)",
  "Next 12 hours rain chance",
  "No hourly rain data",
  "No significant rain expected",
  "Recent searches",
  "Clear",
  "Remove recent search",
  "Alert notifications",
  "Enable browser alerts for selected events",
  "Enabled",
  "Disabled",
  "Browser notifications are blocked. Enable them in browser settings.",
  "Severe weather alerts",
  "Rain expected soon",
  "Poor air quality",
  "Nearby earthquake alerts",
  "Best time to go outside",
  "Based on the next 24 hours AQI",
  "Suggested window",
  "Expected air quality",
];

export const STRING_SET = new Set(UI_STRINGS);
